repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 22.1.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.21.2
- hooks:
  - id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 4.0.1
