# Generated by Django 4.0.3 on 2022-03-22 12:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=80)),
                ('website', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='origincountry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='origincountry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Beans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('roasting_date', models.DateField()),
                ('rating', models.IntegerField(choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Ok'), (2, 'Bad'), (1, 'Very Bad')])),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.origincountry')),
                ('processing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.processing')),
                ('roaster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee.roaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
