# Generated by Django 4.0.3 on 2022-03-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beans',
            name='rating',
            field=models.IntegerField(choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Ok'), (2, 'Bad'), (1, 'Very Bad')], null=True),
        ),
    ]
