# Generated by Django 4.0.3 on 2022-03-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_processing_roaster_origincountry_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='beans',
            constraint=models.UniqueConstraint(fields=('name', 'roaster', 'roasting_date', 'processing'), name='unique_bean_roaster_constraint'),
        ),
    ]
