# Generated by Django 4.0.3 on 2022-03-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_alter_beans_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TastingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='beans',
            name='variety',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beans',
            name='tasting_notes',
            field=models.ManyToManyField(to='coffee.tastingnote'),
        ),
    ]
