# Generated by Django 4.0.3 on 2022-03-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_beans_unique_bean_roaster_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='beans',
            name='unique_bean_roaster_constraint',
        ),
        migrations.AddConstraint(
            model_name='beans',
            constraint=models.UniqueConstraint(fields=('name', 'country', 'roaster', 'roasting_date', 'processing'), name='unique_bean_roaster_constraint'),
        ),
    ]
