# Generated by Django 4.0.3 on 2022-03-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_alter_beans_tasting_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beans',
            name='tasting_notes',
            field=models.ManyToManyField(to='coffee.tastingnote'),
        ),
    ]
