# Generated by Django 4.0.3 on 2022-03-23 18:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0005_alter_beans_tasting_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beans',
            new_name='Coffee',
        ),
    ]
