# Generated by Django 4.0.3 on 2022-03-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0006_rename_beans_coffee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastingnote',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roaster',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tastingnote',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
