# Generated by Django 4.0.3 on 2022-03-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_tastingnote_user_alter_roaster_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processing',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
