# Generated by Django 4.0.3 on 2022-03-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0008_alter_processing_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roaster",
            options={"ordering": ("name",)},
        ),
    ]
