name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: release
        id: create-release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: |
            This is an automated release, see [the changelog](https://github.com/marcelblijleven/beans/blob/master/CHANGELOG.md) for changes
        env:
          GITHUB_TOKEN: ${{ github.token }}