name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: beans.settings.develop
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY_TEST }}
      run: |
        pytest
